#!/usr/bin/env node

describe('Library', () => {
  // Based Library
  require('./lib/statusMessage');
  require('./lib/func');

  // Expanded Library
  require('./lib/converter');
  require('./lib/response');

  // Main Library
  require('./lib/proxy');

  // Util Library
  require('./lib/processActions');
});
